FROM centos:7

LABEL maintainer=mkananovich

RUN yum install -y openldap openldap-servers openldap-clients && yum clean all 

ENV DEBUG_LEVEL=256
EXPOSE 389 636

COPY ./server/ /root

RUN chmod +x /root/provision.sh

CMD ["/root/provision.sh"]